# version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      PGPASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to start...';
        while ! PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -h db -d postgres -c 'SELECT 1' > /dev/null 2>&1; do
          sleep 1;
        done &&
        echo 'PostgreSQL is ready. Checking if database exists...';
        if ! PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -h db -lqt | cut -d \\| -f 1 | grep -qw $POSTGRES_NAME; then
          echo 'Creating database $POSTGRES_NAME...';
          PGPASSWORD=$POSTGRES_PASSWORD createdb -U $POSTGRES_USER -h db $POSTGRES_NAME;
          echo 'Database $POSTGRES_NAME created.';
        else
          echo 'Database $POSTGRES_NAME already exists.';
        fi &&
        echo 'Applying migrations...';
        python manage.py migrate &&
        echo 'Starting Django server...';
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
  db:
    image: postgres:15.10
    env_file:
      - .env
    environment:
      POSTGRES_NAME: drf_hw
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
  redis:
    image: redis:7.4.2
    env_file:
      - .env
    command: redis-server
    expose:
      - "6379"
  celery:
    build: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A config worker -l INFO
    depends_on:
      - redis
  celery_beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l info -S django
    depends_on:
      - celery
      - app
volumes:
  postgres_data:
  static_volume:
