# Generated by Django 5.1.4 on 2025-01-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('id',), 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
